# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

# Triggers the workflow on push or pull request events
on: 
  push:
    paths:
    - 'src/**'
    - 'tests/**'
    - 'setup.py'
    - '.github/workflows/pytest.yml'
    - 'Pipfile*'
    - 'requirements*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      
      - name: Install local packages
        run: |
            pipenv run pip install -e .

      # Cache our requirements using the pipefile.lock as the key
      # as the lock file changes, our requirements will be refetched
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      - name: Run test suite
        run: |
          pipenv run pytest -v
